# Generated by Django 2.2.7 on 2019-11-30 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taulu',
            options={},
        ),
        migrations.AlterModelManagers(
            name='taulu',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='taulu',
            name='expiration',
        ),
        migrations.AddField(
            model_name='taulu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='app.Category'),
        ),
        migrations.AlterField(
            model_name='taulu',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='taulu',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taulu',
            name='name',
            field=models.TextField(),
        ),
    ]
