# Generated by Django 2.2.7 on 2019-12-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191130_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taulu',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
